# Permalinks
permalink:        none

# Setup
url:              https://truongduyng.github.io

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:          ''

title:            Nguyen Truong Duy
name:             Trường Duy

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      >
  I am a classic and modern combination

# The tags listed as entries in the sidebar
sidebar_tags:     []

# Fallback image and color if not overwritten for tag or post
image:            /public/img/nap.jpg
color:            '#A85641'

gems:
  - jekyll-sitemap

author:
  name:           'Trường Duy'
  github:         truongduyng
  photo:          https://avatars0.githubusercontent.com/u/9413750?v=3&s=460

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
    Developer. Beginner of photographer, writer, farmer, entrepreneur. Psychology, sports enthusiasts. Vietnamese.
