### Site info:
title: Nguyen Truong Duy
tagline:
author: Nguyen Truong Duy
email: truongduyng@gmail.com
description: My blog
keywords:
baseurl:
url: "http://ntduy.github.io"


### Personal info and site tools info:
github_username:  ntduy
disqus_shortname: ntduy
favicon:
aboutme:
aboutme_photo: https://lh6.googleusercontent.com/-ZtnchZinRzA/VDSZgBK9IKI/AAAAAAAAABM/MqAWQsK9Eyc/w140-h140-p/Tet2013_Phoninh.jpg # your photo.


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Resent_Posts: "Resent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on "


### your Blogroll info, only name can shown on the page.

Blogroll:
    - name: Nguyen Truong Duy
      href: http://ntduy.blogspot.com
      title: My blogspot


### Build settings
markdown: kramdown
highlighter: pygments
paginate: 5
